version: '2'

services:

  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: secret
      REDMINE_DB_ENCODING: utf8
    depends_on:
      - mysql
    links:
      - mysql:mysql
    restart: always

  mysql:
    image: mysql
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci, --user=root]
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redmine
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    restart: always
